#!python

# Copyright (C) 2017 Daniel Schenk <danielschenk@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

join = os.path.join

env = Environment()

Export(base_env=env)

if ARGUMENTS.get('VERBOSE') != '1':
    env['CCCOMSTR'] = 'Compiling $TARGET'
    env['CXXCOMSTR'] = 'Compiling $TARGET'
    env['LINKCOMSTR'] = 'Linking $TARGET'

env.Append(CPPPATH=[
    # For dependencies expected to be installed on the system:
    # - nlohmann/json (https://github.com/nlohmann/json)
    '/usr/local/include',
])

# Propagate the 'TERM' environment variable from the OS, so tools can decide if they should colorize output
env['ENV']['TERM'] = os.getenv('TERM', 'unknown')

SConscript('PC.scons', variant_dir=Dir('Build/PC'), duplicate=False)
SConscript('Test.scons', variant_dir=Dir('Build/Test'), duplicate=False)

pc = env.Alias('pc', 'Build/PC')
test = env.Alias('test', 'Build/Test')
env.Default(pc)
