#!python

import os
join = os.path.join

env = Environment()

if ARGUMENTS.get('VERBOSE') != '1':
    env['CCCOMSTR'] = 'Compiling $TARGET'
    env['CXXCOMSTR'] = 'Compiling $TARGET'
    env['LINKCOMSTR'] = 'Linking $TARGET'

SConscript('PC.scons', variant_dir=Dir('Build/PC'), exports={'base_env': env}, duplicate=False)
SConscript('Test.scons', variant_dir=Dir('Build/Test'), exports={'base_env': env}, duplicate=False)

pc = env.Alias('pc', 'Build/PC')
test = env.Alias('test', 'Build/Test')
env.Default(pc)
