#!python

import os

join = os.path.join

env = Environment()

Export(base_env=env)

if ARGUMENTS.get('VERBOSE') != '1':
    env['CCCOMSTR'] = 'Compiling $TARGET'
    env['CXXCOMSTR'] = 'Compiling $TARGET'
    env['LINKCOMSTR'] = 'Linking $TARGET'

env.Append(CPPPATH=[
    '/usr/local/Cellar/nlohmann_json/2.1.1/include',
])

SConscript('PC.scons', variant_dir=Dir('Build/PC'), duplicate=False)
SConscript('Test.scons', variant_dir=Dir('Build/Test'), duplicate=False)

pc = env.Alias('pc', 'Build/PC')
test = env.Alias('test', 'Build/Test')
env.Default(pc)
